### ISSUE TITLE
Share FireBase DB Access

### ISSUE THREAD

**Issue by jimishio** [DatameetAMD/open-loo-android#1]
Hello @ndkcha,
Please share firebase access to @dhuma1981, his email is dhuma1981@gmail.com

**Comment by ndkcha** [comment]
I have granted access to @dhuma1981 for firebase console. You will find documentation on how to build an apps from firebase there itself. 
Let me know if you come across any problem.

**Comment by dhuma1981** [comment]
I haven't received anything yet. Can you please share the name of the project over firebase?

**Comment by ndkcha** [comment]
I have granted access to dhuma1981@gmail.com. You will receive an email regarding the link of the console.
Use this link if you haven't received an email: https://open-ahmedabad.firebaseio.com/

If you are making any entries for testing, do not forget to remove them.

Mark `fixed` label as soon as you have access to firebase console.

**Comment by dhuma1981** [comment]
I tried with the link you shared but it shows "There was an error completing your request".

**Comment by ndkcha** [comment]
I have added you again. Can you please check ?

**Comment by dhuma1981** [comment]
Checked, Nothing is there :(

**Comment by shravan91** [comment]
Closing this here. The repo has been moved to https://github.com/DatameetAMD/bucket-list/issues/4
